spring.application.name=cinestream

spring.datasource.url=jdbc:mysql://localhost:3306/cinestream
spring.datasource.username=root
spring.datasource.password=Rionaldo123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true